Name:           ros-jade-nao-moveit-config
Version:        0.0.8
Release:        0%{?dist}
Summary:        ROS nao_moveit_config package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-joint-state-publisher
Requires:       ros-jade-moveit-fake-controller-manager
Requires:       ros-jade-moveit-planners-ompl
Requires:       ros-jade-moveit-ros-move-group
Requires:       ros-jade-moveit-ros-visualization
Requires:       ros-jade-moveit-simple-controller-manager
Requires:       ros-jade-nao-description
Requires:       ros-jade-nao-meshes
Requires:       ros-jade-robot-state-publisher
Requires:       ros-jade-xacro
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-nao-description

%description
An automatically generated package with all the configuration and launch files
for using the NAO robot with the MoveIt Motion Planning Framework

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Wed Feb 03 2016 Mikael Arguedas <mikael.arguedas@gmail.com> - 0.0.8-0
- Autogenerated by Bloom

* Sat Jan 23 2016 Mikael Arguedas <mikael.arguedas@gmail.com> - 0.0.7-0
- Autogenerated by Bloom

* Wed Oct 21 2015 Mikael Arguedas <mikael.arguedas@gmail.com> - 0.0.6-0
- Autogenerated by Bloom

* Tue Aug 04 2015 Mikael Arguedas <mikael.arguedas@gmail.com> - 0.0.5-0
- Autogenerated by Bloom

